spring.application.name=bms_backend
spring.security.user.name=pj
spring.security.user.password=123654

# DB Config
spring.datasource.url=jdbc:postgresql://localhost:5432/api
spring.datasource.username=me
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA/Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
